-- CodeTrain 初期スキーマ
-- DESIGN.md §6「データモデル（主要エンティティ）」および DB_SCHEMA.md に対応する。
-- Aurora Serverless v2 (PostgreSQL) を本番に使うが、Aurora 固有機能は使わない
-- （LOCAL_DEV.md §4.2）。素の PostgreSQL で動くことをローカルで担保する。
--
-- 設計方針（DB_SCHEMA.md §3）:
--   * PK は uuid。アプリ側生成を基本とし、DB デフォルトは gen_random_uuid()。
--   * 回答・タスク消化は追記専用のログ（attempt / daily_task）を真実の源とし、
--     user_progress は再計算可能な表示用キャッシュに徹する。
--   * PoC 段階は GitHub 収集をスキップするため、LLM 生成問題は raw_source の
--     固定ダミー行（下記 LLM_GENERATED_RAW_SOURCE_ID）に紐付ける。

BEGIN;

-- pgcrypto が無い環境向け: PostgreSQL 13+ は gen_random_uuid() を標準搭載する。
-- 念のため pgcrypto も有効化しておく（存在すれば no-op）。
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- 列挙型
-- ---------------------------------------------------------------------------

-- 問題タイプ。DESIGN.md §3 の MVP スコープに挙がっている5種。
CREATE TYPE question_type AS ENUM (
    'code_reading',      -- コード読解
    'output_prediction', -- 出力予測
    'bug_finding',       -- バグ発見
    'fill_in_blank',     -- 穴埋め
    'best_practice'      -- ベストプラクティス選択
);

-- 問題のライフサイクル。DESIGN.md §5 のデータフローに対応。
CREATE TYPE question_status AS ENUM (
    'draft',         -- 生成直後
    'needs_review',  -- 自動検証を通過し、人間レビュー待ち
    'published',     -- 承認済み。配信対象
    'rejected'       -- 却下
);

-- レビュー判定。レビュー待ち中は review_queue.decision を NULL とする。
CREATE TYPE review_decision AS ENUM (
    'approved',   -- 承認
    'rejected',   -- 却下
    'needs_edit'  -- 修正依頼
);

-- ---------------------------------------------------------------------------
-- コンテンツ側
-- ---------------------------------------------------------------------------

-- 取得元コード・出典・ライセンス。
-- DESIGN.md §9（法務・ライセンス制約）により、帰属表示に必要な情報を必ず保持する。
CREATE TABLE raw_source (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    repo_full_name     TEXT        NOT NULL,              -- 例: golang/go
    repo_url           TEXT        NOT NULL,
    commit_sha         TEXT        NOT NULL,
    file_path          TEXT,                              -- LLM のみ生成のときは NULL
    start_line         INTEGER,
    end_line           INTEGER,
    language           TEXT        NOT NULL,              -- 例: go / typescript
    license_spdx       TEXT        NOT NULL,              -- 例: MIT / Apache-2.0 / N/A
    license_url        TEXT,
    author_attribution TEXT,                              -- NOTICE 等の帰属表示テキスト
    s3_key             TEXT,                              -- S3 に置いた原文の位置
    fetched_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (repo_full_name, commit_sha, file_path, start_line, end_line)
);

-- PoC / LLM のみ生成問題が指す固定ダミー行。
-- GitHub 収集を導入したら、実際の収集 row を question.raw_source_id に入れる。
-- ID は codetrain-core / codetrain-pipeline から定数参照するため固定する
-- （domain.LLMGeneratedRawSourceID）。
INSERT INTO raw_source (
    id, repo_full_name, repo_url, commit_sha, file_path,
    language, license_spdx, license_url, author_attribution, s3_key
) VALUES (
    '00000000-0000-0000-0000-000000000001',
    'llm-generated', 'urn:codetrain:llm-generated', '', NULL,
    'n/a', 'N/A', NULL, 'Generated by LLM (no upstream source)', ''
);

-- スキルツリーのトピック。
CREATE TABLE skill (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug          TEXT        NOT NULL UNIQUE,          -- 例: js-basics
    name          TEXT        NOT NULL,
    description   TEXT,
    display_order INTEGER     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- スキルツリーのノード（トピック内の単元）。
-- 先修関係は skill_node_prerequisite（多対多）に分離する。
CREATE TABLE skill_node (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    skill_id      UUID        NOT NULL REFERENCES skill(id) ON DELETE RESTRICT,
    slug          TEXT        NOT NULL,
    name          TEXT        NOT NULL,
    description   TEXT,
    difficulty    SMALLINT    NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
    display_order INTEGER     NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (skill_id, slug)
);

CREATE INDEX idx_skill_node_skill ON skill_node (skill_id, display_order);

-- skill_node 同士の先修関係（多対多）。
-- node_id を解放するのに prerequisite_node_id の履修が必要、という向き。
CREATE TABLE skill_node_prerequisite (
    node_id              UUID NOT NULL REFERENCES skill_node(id) ON DELETE CASCADE,
    prerequisite_node_id UUID NOT NULL REFERENCES skill_node(id) ON DELETE CASCADE,
    PRIMARY KEY (node_id, prerequisite_node_id),
    CHECK (node_id <> prerequisite_node_id)
);

CREATE INDEX idx_skill_node_prereq_prereq ON skill_node_prerequisite (prerequisite_node_id);

-- 設問本体。
-- choices は [{"key":"a","text":"..."}] 形式の JSON 配列、
-- correct_keys は正解の key の配列（単一選択なら要素1つ）。
--
-- raw_source_id は NOT NULL。PoC / LLM のみ生成の場合はダミー行を指す。
-- code_language はタスク（user_task）の言語条件との照合に使う。コード無しの
-- 種別（best_practice の一部など）では NULL。
--
-- prompt_version / model_id / gen_tokens / generated_at は生成メタデータ
-- （OPEN_ISSUES C-3）。手書きのシード問題では NULL になる。
CREATE TABLE question (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    skill_node_id  UUID            REFERENCES skill_node(id) ON DELETE SET NULL,
    raw_source_id  UUID            NOT NULL REFERENCES raw_source(id) ON DELETE RESTRICT,
    type           question_type   NOT NULL,
    status         question_status NOT NULL DEFAULT 'draft',
    difficulty     SMALLINT        NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
    title          TEXT            NOT NULL,
    body           TEXT            NOT NULL,           -- 設問文
    code           TEXT,                               -- 提示するコード片
    code_language  TEXT,
    choices        JSONB           NOT NULL DEFAULT '[]'::jsonb,
    correct_keys   JSONB           NOT NULL DEFAULT '[]'::jsonb,
    explanation    TEXT,
    tags           TEXT[]          NOT NULL DEFAULT '{}',
    prompt_version TEXT,
    model_id       TEXT,
    gen_tokens     INTEGER,
    generated_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX idx_question_status     ON question (status);
CREATE INDEX idx_question_skill_node ON question (skill_node_id);
CREATE INDEX idx_question_tags       ON question USING GIN (tags);
-- タスク割当（type × 言語 × 難易度 で未回答問題を引く）用。
CREATE INDEX idx_question_task_match
    ON question (type, code_language, difficulty)
    WHERE status = 'published';

-- タスク設定画面の選択肢を問題バンクから供給する。
CREATE VIEW available_task_option AS
    SELECT DISTINCT type AS question_type,
           COALESCE(code_language, '') AS language,
           difficulty
      FROM question
     WHERE status = 'published';

-- ---------------------------------------------------------------------------
-- ユーザー側
-- ---------------------------------------------------------------------------

-- 認証情報・プロフィール。
-- external_id は認証基盤上の識別子。AUTH_MODE=cognito では Cognito の sub、
-- AUTH_MODE=dev では X-Dev-User ヘッダの値が入る（LOCAL_DEV.md §5.4）。
-- "user" は予約語のため app_user とする。
CREATE TABLE app_user (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id  TEXT        NOT NULL UNIQUE,
    display_name TEXT        NOT NULL,
    email        TEXT,
    avatar_url   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 表示用キャッシュ。真実の源は attempt（XP）と daily_task（streak）。
-- ここにある集計値はすべてログから再計算可能で、権威データではない。
-- hearts / hearts_updated_at だけはログ非導出のリアルタイム状態として保持する。
-- ゲーム設計パラメータ（OPEN_ISSUES B-3）は未確定のため、計算ロジックは持たせない。
CREATE TABLE user_progress (
    user_id              UUID PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
    xp                   INTEGER     NOT NULL DEFAULT 0,   -- キャッシュ（attempt + 配点表）
    level                INTEGER     NOT NULL DEFAULT 1,   -- キャッシュ（xp から導出）
    streak_days          INTEGER     NOT NULL DEFAULT 0,   -- キャッシュ（daily_task から逆算）
    last_studied_on      DATE,                             -- キャッシュ（daily_task から逆算）
    hearts               SMALLINT    NOT NULL DEFAULT 5,   -- リアルタイム状態
    hearts_updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_skill_node_id UUID       REFERENCES skill_node(id) ON DELETE SET NULL,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 回答履歴。追記専用ログ。正答率・XP・streak の一次情報はここ。
-- 記録後、アプリ側で user_progress / srs_state / user_type_stat / daily_task を更新する。
CREATE TABLE attempt (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        UUID        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    question_id    UUID        NOT NULL REFERENCES question(id) ON DELETE RESTRICT,
    selected_keys  JSONB       NOT NULL DEFAULT '[]'::jsonb,
    is_correct     BOOLEAN     NOT NULL,
    duration_ms    INTEGER,
    answered_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_attempt_user_answered ON attempt (user_id, answered_at DESC);
CREATE INDEX idx_attempt_question      ON attempt (question_id);
-- 「その (type, language) をこのユーザーが何問解いたか」を素早く集計する用途。
CREATE INDEX idx_attempt_user_question ON attempt (user_id, question_id);

-- タスクスロット定義。ユーザーごとに最大5スロット。
-- 例: (slot_no=1, question_type='fill_in_blank', language='python', difficulty=1)
-- difficulty が NULL のときは、サーバがユーザーの正答率から推奨レベルを解決する。
CREATE TABLE user_task (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID          NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    slot_no       SMALLINT      NOT NULL CHECK (slot_no BETWEEN 1 AND 5),
    question_type question_type NOT NULL,
    language      TEXT          NOT NULL DEFAULT '',  -- '' = 言語を問わない
    difficulty    SMALLINT      CHECK (difficulty IS NULL OR difficulty BETWEEN 1 AND 5),
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (user_id, slot_no)
);

-- 日次タスク割当と消化状態。連続タスク消化日数はこのテーブルから逆算する。
-- ホーム画面初回アクセス時に、その日のスロット分を1行ずつ INSERT（冪等）。
-- question_type / language / difficulty は割当時の条件スナップショット
-- （ユーザーが後からスロット設定を変えても当日の判定は動かさないため）。
CREATE TABLE daily_task (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       UUID          NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    activity_date DATE          NOT NULL,
    slot_no       SMALLINT      NOT NULL CHECK (slot_no BETWEEN 1 AND 5),
    question_type question_type NOT NULL,
    language      TEXT          NOT NULL DEFAULT '',
    difficulty    SMALLINT      NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    question_id   UUID          NOT NULL REFERENCES question(id) ON DELETE RESTRICT,
    attempt_id    UUID          REFERENCES attempt(id) ON DELETE SET NULL,
    completed_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (user_id, activity_date, slot_no)
);

CREATE INDEX idx_daily_task_user_date ON daily_task (user_id, activity_date);

-- 種別×言語ごとの正答率キャッシュ（推奨レベル算出用）。
-- 真実の源は attempt。attempt INSERT と同一トランザクションで加算する導出データで、
-- 次のクエリで全再構築できる:
--   SELECT a.user_id, q.type, COALESCE(q.code_language,''),
--          count(*), count(*) FILTER (WHERE a.is_correct)
--     FROM attempt a JOIN question q ON q.id = a.question_id
--    GROUP BY 1,2,3;
CREATE TABLE user_type_stat (
    user_id        UUID          NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    question_type  question_type NOT NULL,
    language       TEXT          NOT NULL DEFAULT '',
    attempts       INTEGER       NOT NULL DEFAULT 0,
    corrects       INTEGER       NOT NULL DEFAULT 0,
    last_difficulty SMALLINT     CHECK (last_difficulty IS NULL OR last_difficulty BETWEEN 1 AND 5),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, question_type, language)
);

-- question × user の間隔反復状態（SM-2 ベース）。
-- 具体仕様は OPEN_ISSUES B-4 で未確定のため、SM-2 が必要とする値の器だけ置く。
CREATE TABLE srs_state (
    user_id          UUID        NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
    question_id      UUID        NOT NULL REFERENCES question(id) ON DELETE RESTRICT,
    easiness         NUMERIC(4,2) NOT NULL DEFAULT 2.5,
    interval_days    INTEGER     NOT NULL DEFAULT 0,
    repetitions      INTEGER     NOT NULL DEFAULT 0,
    due_on           DATE        NOT NULL,
    last_reviewed_at TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, question_id)
);

CREATE INDEX idx_srs_state_due ON srs_state (user_id, due_on);

-- レビュー対象・レビュアー・判定。
-- decision IS NULL がレビュー待ち。判定済み行は履歴として複数残せる。
CREATE TABLE review_queue (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id  UUID            NOT NULL REFERENCES question(id) ON DELETE CASCADE,
    reviewer_id  UUID            REFERENCES app_user(id) ON DELETE SET NULL,
    decision     review_decision,
    notes        TEXT,
    reviewed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ     NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_queue_question ON review_queue (question_id, created_at DESC);
CREATE UNIQUE INDEX idx_review_queue_open
    ON review_queue (question_id)
    WHERE decision IS NULL;

COMMIT;
